### ISSUE TITLE
键盘上点击*时，会出现数字8，密码框会填充圆点

### ISSUE THREAD

**Issue by ahkkfh** [huage2580/PswInputViewDemo#2]
点击控件，出现软键盘，点击*按钮，密码开始填充，最后返回结果为8

**Comment by huage2580** [comment]
(-｡-;)额，为什么数字软键盘会有_号键，因为物理键盘上_和8的对应的，我觉着你是按了物理键盘，如果不是的话，*号键应该是key code=106，或者不会触发keyevent

**Comment by ahkkfh** [comment]
没有特殊设置，用的测试机为魅蓝noto2 ，不确定是否为这个手机特有问题

**Comment by huage2580** [comment]
刚才说错了。正确的key code如下
KEYCODE_0=7;
KEYCODE_1=8;
KEYCODE_2=9;
KEYCODE_3=10;
KEYCODE_4=11;
KEYCODE_5=12;
KEYCODE_6=13;
KEYCODE_7=14;
KEYCODE_8=15;
KEYCODE_9=16;
KEYCODE_STAR=17;
KEYCODE_POUND=18;
如果能接收到key event，*号键应该是17才对，你可以自己断点调试下，因为我没有魅蓝note2，所以无法测试，很抱歉。

**Comment by ahkkfh** [comment]
恩，好的，谢谢

**Comment by huage2580** [comment]
感谢发现问题，经过测试发现是部分输入法对于*号键的处理方式为发送shift+8的key event，已经修复该问题。
